### ISSUE TITLE
$signal: really?

### ISSUE THREAD

**Issue by jpmens** [jalmeroth/homie-python3#1]
[This](https://github.com/jalmeroth/homie-python3/blob/master/homie/main.py#L125) is cute, but do you really want to do this with a `popen()`? It looks horridly ineffective and it's much more _expensive_ in terms of processing than a simple `open()`. :-)

**Comment by jalmeroth** [comment]
@jpmens thanks for your feedback! I really appreciate it. 👍

This is what happens, if you are looking for a solution and copying over the code from StackOverflow. ;-)

I rewrote this function and hope it's more elegant now. Otherwise please don't hold back with suggestions or pull-request.
